// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFUssU7Pv_i52AkVIlLYStQXl_rRyxBs',
    appId: '1:422649370937:web:74b163907a1ff4bcf2b0e8',
    messagingSenderId: '422649370937',
    projectId: 'carwash-65985',
    authDomain: 'carwash-65985.firebaseapp.com',
    storageBucket: 'carwash-65985.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkWUCQI422NdG4kmQlrxJzt2M8-mXQh4',
    appId: '1:422649370937:android:375b50f6323ea932f2b0e8',
    messagingSenderId: '422649370937',
    projectId: 'carwash-65985',
    storageBucket: 'carwash-65985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZdp4VYC-JQ_yGxZ_4qiZtcyMENoXboo',
    appId: '1:422649370937:ios:37a6ea5c7e1e6189f2b0e8',
    messagingSenderId: '422649370937',
    projectId: 'carwash-65985',
    storageBucket: 'carwash-65985.firebasestorage.app',
    iosBundleId: 'com.example.carwashbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZdp4VYC-JQ_yGxZ_4qiZtcyMENoXboo',
    appId: '1:422649370937:ios:37a6ea5c7e1e6189f2b0e8',
    messagingSenderId: '422649370937',
    projectId: 'carwash-65985',
    storageBucket: 'carwash-65985.firebasestorage.app',
    iosBundleId: 'com.example.carwashbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjFUssU7Pv_i52AkVIlLYStQXl_rRyxBs',
    appId: '1:422649370937:web:db2afeffa9da9480f2b0e8',
    messagingSenderId: '422649370937',
    projectId: 'carwash-65985',
    authDomain: 'carwash-65985.firebaseapp.com',
    storageBucket: 'carwash-65985.firebasestorage.app',
  );
}
